import './js/queries';
import './js/home';
// import './js/create-markup-home';
import './js/shopping-list';
import './js/create-markup-shopping';
import './js/btn';
import './js/funds';
import './js/support-ukraine';
import './js/scroll-up';
import './js/theme';
import './js/category-list';
import './js/login-modal';
import './js/swiper';
import './js/menu';
// import './js/create-modal';
